### ISSUE TITLE
[BUG] 個人資料更新優化

### ISSUE THREAD

**Issue by rider159159** [zhao1995chen/wowcho-mgmt-api#74]
- 資料庫要有預設值，例如註冊後，更新資料時，註冊時沒有填寫 name、username、isAllowedNotifications、isSubscribed 、gender
    - 這些資料會是空的，送出時報錯，除非前端判斷，給相對應預設值，不過這方法非正規作法。
    
- Get 時隱藏不必要資訊，以更新個人頁面為例，進入此頁面會先使用 Get 個人資料，將 Get 資料直接用 Vue 做雙向綁定，但會有部分多出來的資料，例如:  `__t:"register"`  、  `createdAt : "2023-04-25T05:33:21.983Z"`  、 `updatedAt:"2023-04-25T05:33:21.983Z"`
    - 除了後端隱藏不必要資訊，也可以讓前端自己解構賦值，可討論，但目前會以後端調整為主。

**Comment by zhao1995chen** [comment]
後續調整如附圖討論結論
![image](https://user-images.githubusercontent.com/53460349/234634858-16865dfe-3cbb-46b6-9d65-0614ef4db47f.png)
